site_name: A股复盘分析
site_url: https://Spectrewsr.github.io/A-market/
repo_name: Spectrewsr/A-market
repo_url: https://github.com/Spectrewsr/A-market/
edit_uri: tree/main/docs
site_description: Spectrewsr and BottleFish's A股复盘分析

theme:
  name: material
  language: zh
  icon:
    logo: material/finance
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
  font: false
  palette:
    - scheme: default

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 2
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex

validation:
  nav:
    omitted_files: info
    not_found: warn
    absolute_links: info
  links:
    not_found: info
    absolute_links: info
    unrecognized_links: info

extra_css:
  - css/custom.css

plugins:
  - search
  - awesome-pages
  - glightbox:
      width: 80%
  - heti
